### ISSUE TITLE
Wrong url in setup.py

### ISSUE THREAD

**Issue by mauritsvanrees** [zopyx/Products.TextIndexNG3#2]
The `url` parameter in `setup.py` points to http://pypi.zopyx.com/pypi/Products.TextIndexNG3 but this server cannot be found. I wonder if it is an internal server.
I suggest pointing to either the official PyPI page or github.

**Comment by zopyx** [comment]
Fixed in 

https://github.com/zopyx/Products.TextIndexNG3/commit/defbdcb5509348861a9b40cf7342f7e4a21a57b0
