### ISSUE TITLE
No more portal_properties.site_properties.default_charset

### ISSUE THREAD

**Issue by pcdummy** [zopyx/Products.TextIndexNG3#3]
Hi,

I tried to install TextIndexNG3 on a Plone 5.0 site.
Switching the indexes to TextIndexNG3 fails as there are no more site_properties.

https://github.com/zopyx/Products.TextIndexNG3/blob/master/Products/TextIndexNG3/skins/textindexng3/txng_convert_indexes.py#L17

Thanks,
René

**Comment by zopyx** [comment]
Fixed in 3.4.12
