### ISSUE TITLE
Search hits artificially restricted when used as SearchableText index in CMF/Plone sites

### ISSUE THREAD

**Issue by darryldixon** [zopyx/Products.TextIndexNG3#5]
Because the ranking_maxhits parameter defaults to a hard-coded amount of 50 and can not be overridden in a property sheet or setup parameter when adding the index, search hits on a CMF/Plone site are extremely artificially limited when TXNG3 is used as the backend for the SearchableText index. Only 50 ranked results are returned out of the index, and if other parameters are specified these results will be further trimmed down so that even fewer are returned to the user.

The only way to override this is the manually add ranking_maxhits to all queries that used the portal_catalog.searchResults interface, eg:
site.portal_catalog.searchResults(SearchableText={'query' : 'search string', 'ranking_maxhits' : 5000})

This could possibly be resolved by allowing ranking_maxhits to be specified when the index is created.

**Comment by zopyx** [comment]
This is not going to be fixed - unless you provide a pull request.
